name: NPM Publish

on:
  push:
    tags: v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
          cache: npm
      - run: npm ci
      - run: npm publish
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}